feat: Create syncDbMigrations() function for running db-migrate against Postgres
imin-ltd/app-utils pull request #1
Opened 2021-01-04 15:41 UTC by lukehesluke

This function will also optionally run a dummy express server in order to appease Heroku's boot timeout

Additional features:

* logger
* postgres
  * postgres connection uses the RDS SSL certificate (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html) rather than `{ rejectUnauthorized: false }`, making the connection more secure
* Sync Migrations CLI (`npx db-migrate-up` & `npx db-migrate-down`)

2021-01-06 16:53 UTC, lukehesluke commented on config/rds-ca-2019-root.pem
> +-----BEGIN CERTIFICATE-----
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

2021-01-06 16:54 UTC, lukehesluke commented on README.md
> +  npx db-migrate-up
A script was needed because the `DATABASE_URL=...` approach does not work as the SSL info cannot be specified in the URL. Also, thought this would be more convenient

2021-01-08 11:56 UTC, civsiv commented on README.md
> +^ This is how you ensure that your app runs migrations when it starts. But how do you actually create migrations in your app:
Maybe something like "The above explains how..." 
I got a little confused and thought you were pointing to the title, not the section above the title

2021-01-08 12:07 UTC, civsiv requested changes

2021-01-08 12:07 UTC, civsiv commented on README.md
> +# app-utils
There's nothing in here about the exported `postgres` and what you can do with that (`pool`, `getConfig`)

2021-01-08 12:07 UTC, civsiv commented on built-types/postgres.d.ts
> +export function pool(postgresConnectionOverride?: PostgresConnectionDetails | null | undefined): Promise<pg.Pool>;
Is there any reason you didn't put `transact` or `query` in this too?
```
/**
 * @param {pg.Pool} pgPool
 * @param {string[]| SQLStatement[]} cmds
 * @param {object} options
 * @param {boolean} options.useTimeout
 * @returns {Promise<QueryResult[]>} Array of responses - one for each command
 */
async function transact(pgPool, cmds, options={ useTimeout: true }) {
  const client = await pgPool.connect();
  const responses = [];
  try {
    await client.query('BEGIN');
    if (options.useTimeout) {
      await client.query('SET LOCAL statement_timeout TO 60000;');
    }
    for (const cmd of cmds) {
      const response = await client.query(cmd);
      responses.push(response);
    }
    await client.query('COMMIT');
    return responses;
  } catch (error) {
    await client.query('END');
    throw error;
  } finally {
    client.release();
  }
}

async function query(pgPool, cmd) {
  try {
    return (await transact(pgPool, [cmd], { useTimeout: false }))[0];
  } catch (error) {
    throw error;
  }
}
```

2021-01-08 12:07 UTC, civsiv commented on built-types/postgres.d.ts
> +export function pool(postgresConnectionOverride?: PostgresConnectionDetails | null | undefined): Promise<pg.Pool>;
Both are functions that are in most if not all `postgres.js` files we have

2021-01-08 12:07 UTC, civsiv commented on README.md
> +## Logger
Maybe a comment here about how Axios errors are specifically handled differently to other errors?

2021-01-08 12:21 UTC, lukehesluke commented on built-types/postgres.d.ts
> +export function pool(postgresConnectionOverride?: PostgresConnectionDetails | null | undefined): Promise<pg.Pool>;
Yes there is. I'm not really sure about `query()`.

For example, in the sellers work, I've just used `pgPool.query(..)` directly (for single queries). `query()` here goes through a transaction just for a single query which seems inefficient. I thought there might be some cases where

1. only a single query is needed - `pgPool.query()`
2. A few queries are needed in succession (but no transaction) - use a pgClient
3. A transaction is needed. Here, I totally agree that the `transact()` function is useful, though I'm not sure why we have this statement timeout as a default option. I think this came out of a specific use case from the past 🤔 ? Can't remember.

So in cases 1. and 2., I think node-postgres' API is sufficient. Case 3 is useful, but it's got some old stuff in. Maybe a bridge to cross if/when an app that uses `app-utils` needs transactions?

2021-01-08 12:33 UTC, lukehesluke commented on README.md
> +^ This is how you ensure that your app runs migrations when it starts. But how do you actually create migrations in your app:
Done

2021-01-08 12:34 UTC, lukehesluke commented on README.md
> +# app-utils
Totes - added

2021-01-08 12:43 UTC, lukehesluke commented on README.md
> +## Logger
Ace! Done. Hopefully now some of our most common conventions are explained somewhere. Just in time for new recruits

2021-01-08 13:19 UTC, civsiv commented on built-types/postgres.d.ts
> +export function pool(postgresConnectionOverride?: PostgresConnectionDetails | null | undefined): Promise<pg.Pool>;
Fair enough!
Maybe one for the future is adding transact and the transaction timeout as an optional env var?

2021-01-08 13:21 UTC, civsiv approved these changes

2021-01-08 14:06 UTC, merged

2021-01-08 14:32 UTC, lukehesluke commented on built-types/postgres.d.ts
> +export function pool(postgresConnectionOverride?: PostgresConnectionDetails | null | undefined): Promise<pg.Pool>;
Yeah to the function. And yeah, timeout if it turns out there's a good reason. We could also do it with a separate function `transactWithStatementTimeout(timeoutMillis, cmds, pgPool) { return (await transact(pgPool, ['SET LOCAL statement_timeout..', ...cmds])).slice(1); }`